
rm = ls

library("gt")
library("readxl")
library("writexl")
library("lubridate")
library("tidyverse")

# 1.Create an R project. Save the dataset and your R code within this project. Load the dataset:comp646_sales.xlsx.
#create data folder
dir.create("data")
getwd()
# copy xlsx into data folder

file.copy("C:\\Users\\zhang\\Desktop\\practice\\data\\comp646_sa.xlsx","data\\comp646_sa.xlsx") 

# 2. Compute the revenue stream for each item (row) using unit_price ∗ quantity. 
# 2. Then aggregate the revenues by country and sort them in descending order by gross revenue.

sales <- read_excel("data/comp646_sa.xlsx")|> mutate(quantity = as.numeric(quantity))
sales_revenue <- sales|>
  mutate(gross_revenue = unit_price*quantity)

sales_by_country <- sales_revenue |>
  group_by(country)|>
  summarise(revenue = sum(gross_revenue,na.rm = TRUE)) |>
  arrange(desc(revenue))|>
  head(5)

sales_by_country <- sales_revenue |>
  group_by(country) |>
  summarise(revenue = sum(gross_revenue, na.rm = TRUE)) |>
  arrange(desc(revenue)) |>
  head(5) |>
  mutate(country = factor(country, levels = country))

# 3. Create a bar chart using ggplot2 that displays sales by country in descending order. Which country generates the highest revenue for the company?
# reorder - reset the display of country vs revenue in descending order
ggplot(sales_by_country, aes(x = reorder(country, -revenue), y = revenue)) +
  geom_bar(stat = "identity")


# 4. What does the following function do, and what is its expected output?
#function(data, selected_country='New Zealand') {
#data$days = as.character(data$days)
#data |>
#filter(country == selected_country) |>
#select(country, year, month, days, unit_price) |>
#group_by(days) |>
#summarize(daily_revenue = sum(unit_price)) |>
#mutate(days = parse_number(days)) |>
#arrange(days)
#}
file.copy("C:\\Users\\zhang\\Desktop\\practice\\data\\data.xlsx","data\\data.xlsx") 

## customise a function for data dataset, with select New Zealand as parameter.with changing the datatype in days column to character. 
## the function contents are, filter the country as New Zealand, and select country, year, month, days, price columns.
## group the data by days with caculating the daily revenue by summing the prices. 
## change the datatype in days to double, and arrange days column in ascending order.



# 5. Use the function and create a ggplot chart for output with respect to the United Kingdom. 
Output_UK <- function(data, selected_country='New Zealand') {
  data$days = as.character(data$days)
  data |>
    filter(country == selected_country) |>
    select(country, year, month, days, unit_price) |>
    group_by(days) |>
    summarize(daily_revenue = sum(unit_price)) |>
    mutate(days = parse_number(days)) |>
    arrange(days)|>
    ggplot(aes(x = days, y = daily_revenue))+
    geom_bar(stat = "identity")
}
Output_UK(sales, selected_country='United Kingdom') 
print(Output_UK(data, selected_country='United Kingdom'))

# 6. Calculate the total revenue generated by each customer. Who is our top customer - the one generating the highest revenue?
sales_revenue |>
  filter(!is.na(customer_id))|>
  group_by(customer_id)|>
  summarise(total_revenue = sum(gross_revenue,na.rm = TRUE))|>
  arrange(desc(total_revenue))|>
  slice(1)

# 7. Calculate the revenue for each invoice. Which invoice generated the highest revenue?
top_sale_invoce <- sales_revenue |>
  filter(!is.na(invoice_no ))|>
  group_by(invoice_no)|>
  summarise(total_revenue = sum(gross_revenue,na.rm = TRUE))|>
  arrange(desc(total_revenue))|>
  slice(1)

# 8. It seems unusual that the highest invoice revenue exceeds the revenue from our top customer.Why does this seem odd? Filter the data for:
# when caculating the customer.id vs sales, the NA values under customer.id columns who have contributed the sales have been removed
# whereas when caculating the invoice no vs sales, there must be an invoice no for each sales, therefore the invoice revenue exceed the top customer sales.
#• the invoices of the customer who generated the highest overall revenue, and

top_revenue<- function(sales_revenue,invoice_no_value){
  sales_revenue |>
    filter(invoice_no ==invoice_no_value)|>
    mutate(total_revenue = sum(gross_revenue,na.rm = TRUE))|>
    arrange(desc(total_revenue))|>
    slice(1)
}
top_revenue(sales_revenue, top_sale_invoce$invoice_no)

#• the invoice with the highest individual revenue.

sales_revenue |>
  select(invoice_no,gross_revenue)|>
  arrange(desc(gross_revenue))|>
  slice(1)


